name: Daily updates

on:
  schedule:
    - cron: '00 19 * * *'
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install and run
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python daily_jobs.py
        env:
          VSF_BOT_TOKEN: ${{ secrets.VSF_BOT_TOKEN }}
          ZOOM_API_KEY: ${{ secrets.ZOOM_API_KEY }}
          ZOOM_API_SECRET: ${{ secrets.ZOOM_API_SECRET }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          HOST_KEY_SALT: ${{ secrets.SC_HOST_KEY_SALT }}
