name: Video upload
on:
  repository_dispatch:
    types: [publish-youtube-video]


jobs:
  video_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Trim and upload the video
        run: python video.py
        env:
          ISSUE_NUMBER: ${{ github.event.client_payload.issue }}
          VSF_BOT_TOKEN: ${{ secrets.VSF_BOT_TOKEN }}
          ZOOM_API_KEY: ${{ secrets.ZOOM_API_KEY }}
          ZOOM_API_SECRET: ${{ secrets.ZOOM_API_SECRET }}
          YOUTUBE_CREDENTIALS: ${{ secrets.YOUTUBE_CREDENTIALS }}
          