name: Send an email announcement
on:
  repository_dispatch:
    types: [email]


jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send email
        run: python send_email.py
        env:
          ISSUE_NUMBER: ${{ github.event.client_payload.issue }}
          VSF_BOT_TOKEN: ${{ secrets.VSF_BOT_TOKEN }}
          ZOOM_ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}
          ZOOM_CLIENT_ID: ${{ secrets.ZOOM_CLIENT_ID }}
          ZOOM_CLIENT_SECRET: ${{ secrets.ZOOM_CLIENT_SECRET }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}

